import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const bloomLevel = v.union(
  v.literal("remember"),
  v.literal("understand"),
  v.literal("apply"),
  v.literal("analyze"),
  v.literal("evaluate"),
  v.literal("create"),
);

export default defineSchema({
  classes: defineTable({
    name: v.string(),
    grade: v.number(),
    section: v.string(),
    subject: v.string(),
    board: v.literal("CBSE"),
    academicYear: v.string(),
  }),
  students: defineTable({
    classId: v.id("classes"),
    name: v.string(),
    rollNumber: v.string(),
    status: v.union(v.literal("active"), v.literal("inactive")),
    supportNeeds: v.array(v.string()),
    priorScorePercent: v.optional(v.number()),
    misconceptions: v.array(v.string()),
  }).index("by_class", ["classId"]),
  curriculumNodes: defineTable({
    board: v.literal("CBSE"),
    grade: v.number(),
    subject: v.string(),
    chapter: v.string(),
    concept: v.string(),
    skill: v.string(),
    learningOutcome: v.string(),
    bloomLevel,
  }).index("by_scope", ["board", "grade", "subject"]),
  assessmentPlans: defineTable({
    classId: v.optional(v.id("classes")),
    title: v.string(),
    className: v.string(),
    board: v.literal("CBSE"),
    grade: v.number(),
    subject: v.string(),
    chapter: v.string(),
    concepts: v.array(v.string()),
    bloomLevels: v.array(bloomLevel),
    questionCount: v.number(),
    totalMarks: v.number(),
    durationMinutes: v.number(),
    objectiveRatio: v.number(),
    instructions: v.string(),
    status: v.union(v.literal("draft"), v.literal("ready_for_generation"), v.literal("generated"), v.literal("published")),
    aiRequest: v.object({
      task: v.literal("generate_assessment"),
      schemaVersion: v.literal("1.0"),
      humanReviewRequired: v.literal(true),
    }),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_status", ["status"]),
  submissions: defineTable({
    assessmentPlanId: v.id("assessmentPlans"),
    studentId: v.id("students"),
    answers: v.array(v.object({ questionId: v.string(), response: v.string() })),
    status: v.union(v.literal("draft"), v.literal("submitted"), v.literal("queued_for_evaluation")),
    submittedAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_assessment", ["assessmentPlanId"]),
  workflowRuns: defineTable({
    workflowType: v.union(v.literal("generateAssessment"), v.literal("evaluateSubmission"), v.literal("generateWeeklyPlan")),
    entityId: v.string(),
    status: v.union(
      v.literal("queued"),
      v.literal("validating"),
      v.literal("running"),
      v.literal("awaiting_review"),
      v.literal("completed"),
      v.literal("failed_retryable"),
      v.literal("failed_terminal"),
      v.literal("cancelled"),
    ),
    currentStage: v.string(),
    agentTrace: v.array(v.object({ stage: v.string(), message: v.string(), at: v.number() })),
    createdAt: v.number(),
  }).index("by_entity", ["entityId"]),
});
